/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.ClienteDAO;
import dao.ItemNotaFiscalDAO;
import dao.NotaFiscalDAO;
import dao.ProdutoDAO;
import java.time.LocalDate;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Cliente;
import model.ItemNotaFiscal;
import model.NotaFiscal;
import model.Produto;

/**
 *
 * @author teusi
 */
public class FrmNotaFiscal extends javax.swing.JFrame {

    /**
     * Creates new form FrmNotaFiscal
     */
    public FrmNotaFiscal() {
        initComponents();
        configurarEventos();
        carregarClientes();
        carregarProdutos();
        inicializarFormulario();
    }

    private void configurarEventos() {
        AdicionarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdicionarItemActionPerformed(evt);
            }
        });

        finalizarNF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizarNFActionPerformed(evt);
            }
        });

        comboProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarValorProdutoSelecionado();
            }
        });
    }

    private void inicializarFormulario() {
        txtDataEmissaoNf.setText(LocalDate.now().toString());
        txtSubtotal.setText("0.00");
        txtTotalNf.setText("0.00");
        valorUnitario.setText("0.00");
        txtQuantidade.setValue(1);
        atualizarTabelaItens();
    }

    private void carregarClientes() {
        comboCliente.removeAllItems();
        List<Cliente> clientes = new ClienteDAO().listar();
        for (Cliente c : clientes) {
            comboCliente.addItem(c.getId() + " - " + c.getNome());
        }
    }

    private void carregarProdutos() {
        comboProduto.removeAllItems();
        List<Produto> produtos = new ProdutoDAO().listar();
        for (Produto p : produtos) {
            comboProduto.addItem(p.getId() + " - " + p.getNome());
        }
        atualizarValorProdutoSelecionado();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        valorUnitario = new javax.swing.JTextField();
        txtSubtotal = new javax.swing.JTextField();
        txtTotalNf = new javax.swing.JTextField();
        txtDataEmissaoNf = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaEmissaoNf = new javax.swing.JTable();
        CriarNF = new javax.swing.JButton();
        AdicionarItem = new javax.swing.JButton();
        finalizarNF = new javax.swing.JButton();
        ImprimirNf = new javax.swing.JButton();
        gerarPdf = new javax.swing.JButton();
        comboCliente = new javax.swing.JComboBox<>();
        comboProduto = new javax.swing.JComboBox<>();
        txtQuantidade = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("EMISSÃO DE NOTA FISCAL");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Dados da Nota Fiscal");

        jLabel2.setText("Data:");

        jLabel3.setText("Cliente:");

        jLabel4.setText("Produto:");

        jLabel6.setText("Quantidade:");

        jLabel7.setText("Valor Unitário:");

        jLabel8.setText("Subtotal:");

        jLabel9.setText("Total NF:");

        valorUnitario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorUnitarioActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Itens da Nota Fiscal");

        tabelaEmissaoNf.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Produto", "Quantidade", "Valor Unitário", "Subtotal"
            }
        ));
        jScrollPane1.setViewportView(tabelaEmissaoNf);

        CriarNF.setText("Criar NF");
        CriarNF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CriarNFActionPerformed(evt);
            }
        });

        AdicionarItem.setText("Adicionar Item");

        finalizarNF.setText("Finalizar NF");

        ImprimirNf.setText("Imprimir");

        gerarPdf.setText("Gerar PDF");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1)
                            .addComponent(jLabel5))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDataEmissaoNf, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                            .addComponent(comboCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboProduto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtTotalNf, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(valorUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(54, 54, 54))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CriarNF)
                                .addGap(18, 18, 18)
                                .addComponent(AdicionarItem)
                                .addGap(18, 18, 18)
                                .addComponent(finalizarNF)
                                .addGap(18, 18, 18)
                                .addComponent(ImprimirNf)
                                .addGap(18, 18, 18)
                                .addComponent(gerarPdf)))
                        .addGap(0, 147, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(comboCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDataEmissaoNf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(valorUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtTotalNf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(comboProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CriarNF)
                    .addComponent(AdicionarItem)
                    .addComponent(finalizarNF)
                    .addComponent(ImprimirNf)
                    .addComponent(gerarPdf))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void valorUnitarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorUnitarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorUnitarioActionPerformed

    private int nfAtual = -1;
    private double totalNota = 0;

    private int extrairIdSelecionado(Object selecionado, String mensagemErro) {
        if (selecionado == null) {
            throw new IllegalArgumentException(mensagemErro);
        }

        String texto = selecionado.toString().trim();
        if (texto.isEmpty()) {
            throw new IllegalArgumentException(mensagemErro);
        }

        // Aceita formato "1", "1 - Nome" ou "1: Nome"
        String idTexto = texto.split("[^0-9]", 2)[0];
        if (idTexto.isEmpty()) {
            throw new IllegalArgumentException(mensagemErro);
        }
        return Integer.parseInt(idTexto);
    }

    private int obterIdClienteSelecionado() {
        return extrairIdSelecionado(comboCliente.getSelectedItem(), "Selecione um cliente válido.");
    }

    private int obterIdProdutoSelecionado() {
        return extrairIdSelecionado(comboProduto.getSelectedItem(), "Selecione um produto válido.");
    }

    private Produto obterProdutoSelecionado() {
        int idProduto = obterIdProdutoSelecionado();
        Produto produto = new ProdutoDAO().buscarPorId(idProduto);
        if (produto == null) {
            throw new IllegalArgumentException("Produto não encontrado no banco de dados.");
        }
        return produto;
    }

    private void atualizarValorProdutoSelecionado() {
        try {
            if (comboProduto.getSelectedItem() == null) {
                return;
            }
            Produto produto = obterProdutoSelecionado();
            valorUnitario.setText(String.format(java.util.Locale.US, "%.2f", produto.getValor()));
            atualizarSubtotal();
        } catch (Exception e) {
            // evita quebrar a carga inicial da tela caso não haja produtos
        }
    }

    private void atualizarSubtotal() {
        try {
            int quantidade = Integer.parseInt(txtQuantidade.getValue().toString());
            double valor = Double.parseDouble(valorUnitario.getText().trim().replace(",", "."));
            txtSubtotal.setText(String.format(java.util.Locale.US, "%.2f", quantidade * valor));
        } catch (Exception e) {
            txtSubtotal.setText("0.00");
        }
    }

    private void atualizarTabelaItens() {
        DefaultTableModel model = (DefaultTableModel) tabelaEmissaoNf.getModel();
        model.setRowCount(0);
    }
    
    private void CriarNFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CriarNFActionPerformed
        try {
            NotaFiscal nf = new NotaFiscal();
            nf.setFkCliente(obterIdClienteSelecionado());
            nf.setDataEmissao(java.sql.Date.valueOf(txtDataEmissaoNf.getText().trim())); // formato: yyyy-MM-dd
            nf.setValorTotal(0);

            NotaFiscalDAO dao = new NotaFiscalDAO();
            nfAtual = dao.inserir(nf);

            if (nfAtual > 0) {
                totalNota = 0;
                txtTotalNf.setText("0.00");
                atualizarTabelaItens();
                JOptionPane.showMessageDialog(this, "NF criada com código: " + nfAtual);
            } else {
                JOptionPane.showMessageDialog(this, "Não foi possível criar a NF.");
            }
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, "Dados inválidos: " + e.getMessage());
        }
    }//GEN-LAST:event_CriarNFActionPerformed

    private void AdicionarItemActionPerformed(java.awt.event.ActionEvent evt) {
        if (nfAtual <= 0) {
            JOptionPane.showMessageDialog(this, "Crie a NF antes de adicionar itens.");
            return;
        }

        try {
            Produto produto = obterProdutoSelecionado();
            int quantidade = Integer.parseInt(txtQuantidade.getValue().toString());
            if (quantidade <= 0) {
                throw new IllegalArgumentException("Quantidade deve ser maior que zero.");
            }

            double unitario = produto.getValor();
            double subtotal = unitario * quantidade;

            ItemNotaFiscal item = new ItemNotaFiscal();
            item.setFkNf(nfAtual);
            item.setFkProd(produto.getId());
            item.setQuantidade(quantidade);
            item.setValorUnitario(unitario);
            item.setSubtotal(subtotal);

            new ItemNotaFiscalDAO().inserir(item);

            DefaultTableModel model = (DefaultTableModel) tabelaEmissaoNf.getModel();
            model.addRow(new Object[]{
                model.getRowCount() + 1,
                produto.getNome(),
                quantidade,
                String.format(java.util.Locale.US, "%.2f", unitario),
                String.format(java.util.Locale.US, "%.2f", subtotal)
            });

            totalNota += subtotal;
            txtSubtotal.setText(String.format(java.util.Locale.US, "%.2f", subtotal));
            txtTotalNf.setText(String.format(java.util.Locale.US, "%.2f", totalNota));
            txtQuantidade.setValue(1);

            JOptionPane.showMessageDialog(this, "Item adicionado e salvo no banco.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao adicionar item: " + e.getMessage());
        }
    }

    private void finalizarNFActionPerformed(java.awt.event.ActionEvent evt) {
        if (nfAtual <= 0) {
            JOptionPane.showMessageDialog(this, "Nenhuma NF foi criada.");
            return;
        }

        try {
            new NotaFiscalDAO().atualizarTotal(nfAtual, totalNota);
            JOptionPane.showMessageDialog(this, "NF finalizada com total R$ " + String.format(java.util.Locale.US, "%.2f", totalNota));
            nfAtual = -1;
            totalNota = 0;
            txtTotalNf.setText("0.00");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao finalizar NF: " + e.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmNotaFiscal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmNotaFiscal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmNotaFiscal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmNotaFiscal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmNotaFiscal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdicionarItem;
    private javax.swing.JButton CriarNF;
    private javax.swing.JButton ImprimirNf;
    private javax.swing.JComboBox<String> comboCliente;
    private javax.swing.JComboBox<String> comboProduto;
    private javax.swing.JButton finalizarNF;
    private javax.swing.JButton gerarPdf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaEmissaoNf;
    private javax.swing.JTextField txtDataEmissaoNf;
    private javax.swing.JSpinner txtQuantidade;
    private javax.swing.JTextField txtSubtotal;
    private javax.swing.JTextField txtTotalNf;
    private javax.swing.JTextField valorUnitario;
    // End of variables declaration//GEN-END:variables
}
